title: Masayoshi Kataoka
email: mkataoka73@gmail.com
description: Masayoshi Kataoka's home page.

url: "https://jlmercury.github.io"

future: true
timezone: Asia/Tokyo

collections_dir: collections

collections:
   beers:
     output: true
     url: /favorites/beers.html
   books:
     output: true
     url: /favorites/books.html
   musics:
     output: true
     url: /favorites/musics.html
   movies:
     output: true
     url: /favorites/movies.html
