title: My Personal Site
email: mkataoka73@gmail.com
description:

url: "https://jlmercury.github.io"

future: true
timezone: Asia/Tokyo

collections_dir: collections

collections:
   beers:
     output: true
   books:
     output: true
   musics:
     output: true
   movies:
     output: true
